---
creation_rules:
  - path_regex: manifests/.*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: >-
      12ABFF8D5FFD0A910EB7F360B968CC2CD1CE08E4,
      C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4

  - path_regex: talosconfig
    encrypted_regex: ^key$
    pgp: C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4

  - path_regex: kubeconfig
    encrypted_regex: ^client-key-data$
    pgp: C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4

  - path_regex: secrets.yaml
    encrypted_regex: ^(secret|bootstraptoken|secretboxencryptionsecret|token|key)$
    pgp: C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4
