---
creation_rules:
  - path_regex: manifests/*.yaml
    encrypted_regex: ^(data|stringData)$
    pgp: >-
      12ABFF8D5FFD0A910EB7F360B968CC2CD1CE08E4,
      C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4
