apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+Xxf4x3/X2X5L71b4DGiRiJ8l7qkw5CU6uk782J9xK+Kk64LEBT5DZ/Lrwfhu68zkHJelTYV4A/ds8w+ZAb3RTpcOgP/XBHEZOd6mWBmiBAGf9CAkN4cD5GT5iJk+T/jwwELQ8ykvE71PhH7S4YVm20eeT2Gr7rWUEdBEnZWzFYZcgstb2GBLsago7pvn3diI5pSBi8e4DfLXEEYS/Zc3s71mbFG+GYgDbyDtzNvVgrnmf75bcQkzHcFPrxnspcuVslVM//6greYEqt8e6qxMnxxobShcWU1z3q/bMPhEfyU6tmKMorf8OrnUsIwLFJd7+2nRaffep0=,iv:mpKMjZbnDwUYv321hhZTugnMJOFGfk9z9IfQQTam9rk=,tag:pDgxubqf4jM+OXQMU9o6NQ==,type:str]
kind: Secret
metadata:
    name: docker-hub-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-24T06:41:32Z"
    mac: ENC[AES256_GCM,data:0OpGYoKIiHLDTysQuPDl4idcd+QE9iK/vAPWebI3kFMPTSfaHpuEw5NMeFcVTvaJECXOEvcPZs5+MvlowKVwcvuI63sbfgVmmBPhV4g8rzhNdoUAct7Sum+iuvCbQ+/u3ciUDQER7zeNhj8D+C/5nsUKSNzS/qJlzX82XV6984E=,iv:aTgCA+u8VfTdYDNg/nhl+qSmNUlvhUMXnEpctMHzbsw=,tag:0T0OOASGtuHuRyBZogc7+Q==,type:str]
    pgp:
        - created_at: "2024-04-24T06:41:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5mMqnQNemXcSAQdAAEisO+SnZ/DekSPajjnQR/z77QiIMg/T4/BBDoSnVyQw
            w5eRi8+z+U8W2K2S0YVDjflKgIcvqHNk+X6G5mi5qY6ChhpTCAUNJrBiOvmyJcnP
            1GgBCQIQuXxT8wD34tc2fTnmqUkKFIPkt+QOBAnoeZ+6mBMf8xxiYmiU0isLyh5y
            jQOdgNHHjTrm4ANTv08YKD9ZTVR6/+W3q9Y69COUvyId4WsH4LwEuqreZdXwczZC
            3IT61SpiJirIqQ==
            =0LDe
            -----END PGP MESSAGE-----
          fp: 12ABFF8D5FFD0A910EB7F360B968CC2CD1CE08E4
        - created_at: "2024-04-24T06:41:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUuTPxQfQ2pESAQdAhLNNZ5bnU5YDMz6IY3xtEovTcK9Jw+JVoz1mlabLXCsw
            PLFKKcP97kvlXhGz8waQVReJJU2OGYUkD/qpq3rlDiC57OyQocanlwA/kbRipWxV
            1GgBCQIQU02wFHSKAsTSYLH8g6ii9MnL2Pn8tllgmrBG7HcXhLbV6GZS7ILQdOjr
            szhgFi/1QXqQYNnaUsHM5wTUMEHzRtrfLEU3Z28z02UKd6WHkxh30ci/DoVSfx3u
            OgqEeYUpt6skUQ==
            =d2YZ
            -----END PGP MESSAGE-----
          fp: C1B127FE85D8F1C17AAC236F2F67BCE9A85EF7C4
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
